services:
  prosody:
    build: ./prosody
    container_name: prosody
    restart: unless-stopped
    networks:
      - xmpp_network
    ports:
      - "5222:5222"  # XMPP client connections
      - "5269:5269"  # Server-to-server connections
      - "5280:5280"  # HTTP binding / BOSH (if enabled)
    volumes:
      - ./prosody/prosody-config:/etc/prosody   # Place your custom configuration files here
      - ./prosody/prosody-data:/var/lib/prosody   # Persistent data storage

    command: ["prosody"]
    # Optional environment variables – adjust as needed for your image
    # environment:
    #   - PROSODY_DOMAIN=example.com
    #   - PROSODY_ADMINS=admin@example.com

  agent:
    build: .
    container_name: agent
    restart: unless-stopped
    networks:
      - xmpp_network
    depends_on:
      - prosody
    environment:
      XMPP_SERVER: prosody
      XMPP_PORT: 5222
      XMPP_USERNAME: "camera_agent"
      XMPP_PASSWORD: "top_secret"
      PYTHONUNBUFFERED: 1
    volumes:
      - ./src:/app/src  # Map local src directory to /app/src in the container
    devices:
      - /dev/video0:/dev/video0  # Give access to the camera device
    privileged: true

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"    # MQTT protocol
      - "9001:9001"    # WebSocket protocol
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped

networks:
  xmpp_network:

volumes:
  prosody_data:
  prosody_config:
  prosody_logs: