services:
  prosody:
    build: ./prosody
    container_name: prosody
    restart: unless-stopped
    networks:
      - xmpp_network
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
    volumes:
      - ./prosody/prosody-config:/etc/prosody
      - ./prosody/prosody-data:/var/lib/prosody
    command: ["prosody"]

  emqx:
    image: emqx/emqx:5.8.6
    container_name: emqx
    restart: unless-stopped
    networks:
      - xmpp_network
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "8084:8084"
      - "18083:18083"

  agent:
    build: .
    container_name: agent
    restart: unless-stopped
    networks:
      - xmpp_network
    depends_on:
      - prosody
      - emqx
    environment:
      XMPP_SERVER: prosody
      XMPP_PORT: 5222
      XMPP_USERNAME: "camera_agent"
      XMPP_PASSWORD: "top_secret"
      MQTT_BROKER: emqx
      MQTT_PORT: 1883
      PYTHONUNBUFFERED: 1
    volumes:
      - ./src:/app/src
    devices:
      - /dev/video0:/dev/video0
    privileged: true

  gatehub:
    build: ./ble-gates/gatehub
    container_name: gatehub
    restart: unless-stopped
    networks:
      - xmpp_network
    environment:
      - MQTT_BROKER=emqx
      - MQTT_PORT=1883
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev:/dev
      - ./ble-gates/gatehub:/app

  roboticarm:
    build:
      context: https://github.com/isc-bit-busters/RoboticArm.git
    container_name: roboticarm_container
    networks:
      - xmpp_network

networks:
  xmpp_network:

volumes:
  prosody_data:
  prosody_config:
  prosody_logs: