services:
  prosody:
    build: ./prosody
    container_name: prosody
    restart: unless-stopped
    networks:
      - xmpp_network
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
    volumes:
      - ./prosody/prosody-config:/etc/prosody
      - ./prosody/prosody-data:/var/lib/prosody
    command: ["prosody"]

  agent:
    build: .
    container_name: agent
    restart: unless-stopped
    networks:
      - xmpp_network
    depends_on:
      - prosody
      - emqx
    environment:
      XMPP_SERVER: prosody
      XMPP_PORT: 5222
      XMPP_USERNAME: "camera_agent"
      XMPP_PASSWORD: "top_secret"
      MQTT_BROKER: localhost
      MQTT_PORT: 1883
      PYTHONUNBUFFERED: 1
    volumes:
      - ./src:/app/src
    devices:
      - /dev/video0:/dev/video0
    privileged: true

  emqx:
    image: emqx/emqx:5.8.6
    container_name: emqx
    restart: unless-stopped
    networks:
      - xmpp_network
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "8084:8084"
      - "18083:18083"

  gate1:
    build: ./ble-gates/gate1
    container_name: gate1
    restart: unless-stopped
    environment:
      - BLE_ADDRESS=DF:CB:A0:71:A8:6C
      - MQTT_BROKER=192.168.88.249
      - MQTT_PORT=1883
      - MQTT_TOPIC=gate1/ir
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev:/dev


  gate2:
    build: ./ble-gates/gate2
    container_name: gate2
    restart: unless-stopped
    environment:
      - BLE_ADDRESS=:D7:09:01:AC:78:08
      - MQTT_BROKER=192.168.88.249
      - MQTT_PORT=1883
      - MQTT_TOPIC=gate2/ir
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev:/dev

networks:
  xmpp_network:

volumes:
  prosody_data:
  prosody_config:
  prosody_logs:
